### ISSUE TITLE
Transfering wordle content between devices

### ISSUE THREAD

**Issue by dearmash** [sethmlarson/sethmlarson.dev#21]

**Comment by dearmash** [comment]
I meant to type more sorry.

If you go to chrome dev tools: application tab -> local storage -> nytimes.com

You can see where the keys are being persisted there now.

The important keys seem to be: 'nyt-wordle-moogle/ANON' and 'nyt-wordle-statistics'

If you can somehow construct those via json, then via javascript call the 'window.localStorage.setItem(key, jsonstr)' method, it might work. It might have to be implemented more as a bookmarklet, vs as a direct URL.

I was able to copy from one browser to another directly via the dev tools, didn't try to fancy it up. Worked between mobile devices as well via https://developer.chrome.com/docs/devtools/remote-debugging/

Hope it helps, and hope chatting via github issues actually works.

**Comment by trickinit** [comment]
@dearmash Any luck getting this to work? I had to reset my phone a week ago and lost my stats. I'm trying to figure out how to restore them before linking it up to an NYT account.

**Comment by sethmlarson** [comment]
Thanks for the interest here, however I've moved on from Wordle so likely won't be implementing this. Closing this issue.

**Comment by wshanks** [comment]
https://github.com/MageJohn/wordle-stats-mover has a nice bookmarklet for moving wordle stats like dearmarsh suggested above. I mention it here because the [blog post](https://sethmlarson.dev/wordle-stats) comes up much more readily for me in internet searches than that bookmarklet (I had to do a GitHub search to find it; I couldn't find a working one with a general internet search).
